Feature/ta 5 latest works
vtilve-cci/reen-webiste pull request #2
Opened 2021-04-12 05:54 UTC by riddhinaik-cci

@vtilve-cci Latest works section completed. Please review the code.

2021-04-14 13:47 UTC, vtilve-cci requested changes
Fix the comments mentioned and Complete the pull request

2021-04-14 13:47 UTC, vtilve-cci commented on index.html
> +                <div class="text-center pb-4">
Why is this placeholder div created? This was explained in our last review as NOT to use placeholder divs just to add utility classes. Instead, add the utility class to the individual element tag.

2021-04-14 13:47 UTC, vtilve-cci commented on index.html
> +                        <div class="card grand-motel">
Global for the Large thumbnails: On hover of the card, you need to show the green overlay with the plus icon and change the title text color to green at the same time. Currently, you need to hover on an individual elements to see the effect.

2021-04-14 13:47 UTC, vtilve-cci commented on index.html
> +                                <span>Identity</span>
The spacing between the p and span is NOT the same as that seen in the PSD. Please fix it.

2021-04-14 13:47 UTC, vtilve-cci commented on index.html
> +                                    <a href="#" class="icon">
Global: 
- While working on the project make sure you understand the links and if NOT aware contact your supervisor and try to know which link to be added.
- If NO link is known for the href, instead of just adding '#' practice of adding 'javascript:void(0);'.

2021-04-14 13:47 UTC, vtilve-cci commented on content/sass/modules/_card.scss
> +            -webkit-transform: translate(-50%, -50%);
Global: For transforms, transitions, keyframes, etc try using mixin.
https://medium.com/@vasdekijoanna/sass-scss-useful-mixins-for-faster-development-b5ac5d4a5de#:~:text=To%20create%20a%20mixin%20we,the%20name%20of%20the%20mixin.

2021-04-15 09:26 UTC, riddhinaik-cci commented on content/sass/modules/_card.scss
> +        font-size: 1.5rem !important;
-important removed.
-mixin for fonts was used.

2021-04-15 09:27 UTC, riddhinaik-cci commented on content/sass/modules/_card.scss
> +        font-size: 14px;
-font-size mixin was used.

2021-04-15 09:29 UTC, riddhinaik-cci commented on content/sass/modules/_card.scss
> +        @include media-breakpoint-up(lg) {
-sorry for that. I removed one of the breakpoint

2021-04-15 09:29 UTC, riddhinaik-cci commented on index.html
> +                <div class="text-center pb-4">
-Fixed the issues.

2021-04-15 09:31 UTC, riddhinaik-cci commented on index.html
> +                        <div class="card grand-motel">
-I tried to fix this one but I am not sure if its correct. So do let me know if any further changes required.

2021-04-15 09:31 UTC, riddhinaik-cci commented on index.html
> +                                <span>Identity</span>
-fixed the issue.

2021-04-15 09:33 UTC, riddhinaik-cci commented on index.html
> +                                    <a href="#" class="icon">
-Noted the above points.
-Added javascript void.

2021-04-15 09:33 UTC, riddhinaik-cci commented on content/sass/modules/_card.scss
> +            -webkit-transform: translate(-50%, -50%);
-Made use of a few mixin. Let me know if its the correct way.

2021-04-16 11:39 UTC, closed without merging